export const airports = [
  { id: 1, code: "ATL", city: "Atlanta" },
  { id: 2, code: "LAX", city: "Los Angeles" },
  { id: 3, code: "ORD", city: "Chicago" },
  { id: 4, code: "DFW", city: "Dallas" },
  { id: 5, code: "DEN", city: "Denver" },
  { id: 6, code: "JFK", city: "New York" },
  { id: 7, code: "SFO", city: "San Francisco" },
  { id: 8, code: "SEA", city: "Seattle" },
  { id: 9, code: "LAS", city: "Las Vegas" },
  { id: 10, code: "MCO", city: "Orlando" },
  { id: 11, code: "CLT", city: "Charlotte" },
  { id: 12, code: "PHX", city: "Phoenix" },
  { id: 13, code: "IAH", city: "Houston" },
  { id: 14, code: "MIA", city: "Miami" },
  { id: 15, code: "EWR", city: "Newark" },
  { id: 16, code: "BOS", city: "Boston" },
  { id: 17, code: "MSP", city: "Minneapolis" },
  { id: 18, code: "FLL", city: "Fort Lauderdale" },
  { id: 19, code: "DTW", city: "Detroit" },
  { id: 20, code: "PHL", city: "Philadelphia" },
  { id: 21, code: "SAN", city: "San Diego" },
  { id: 22, code: "TPA", city: "Tampa" },
  { id: 23, code: "BWI", city: "Baltimore" },
  { id: 24, code: "SLC", city: "Salt Lake City" },
  { id: 25, code: "HNL", city: "Honolulu" },
  { id: 26, code: "MDW", city: "Chicago" },
  { id: 27, code: "DCA", city: "Washington" },
  { id: 28, code: "STL", city: "St. Louis" },
  { id: 29, code: "PDX", city: "Portland" },
  { id: 30, code: "AUS", city: "Austin" },
];

export const flights = [
  {
    id: 1,
    from: "ATL",
    to: "LAX",
    departDay: "23-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 1,
    stopLength: "4h 05m in ICN",
    price: 250,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 2,
    from: "LAX",
    to: "JFK",
    departDay: "23-12-2024",
    airline: "American Airlines",
    fromTime: "01:00 PM",
    toTime: "09:00 PM",
    stops: 1,
    stopLength: "2h 45m in HNL",
    price: 300,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 3,
    from: "DEN",
    to: "ORD",
    departDay: "23-12-2024",
    airline: "United Airlines",
    fromTime: "07:30 AM",
    toTime: "10:00 AM",
    stops: 0,
    stopLength: null,
    price: 180,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 4,
    from: "SFO",
    to: "SEA",
    departDay: "23-12-2024",
    airline: "Alaska Airlines",
    fromTime: "02:00 PM",
    toTime: "03:30 PM",
    stops: 0,
    stopLength: null,
    price: 150,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 5,
    from: "MIA",
    to: "ATL",
    departDay: "23-12-2024",
    airline: "Spirit Airlines",
    fromTime: "06:00 AM",
    toTime: "08:15 AM",
    stops: 1,
    stopLength: "50m in HKG",
    price: 120,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 6,
    from: "PHX",
    to: "CLT",
    departDay: "23-12-2024",
    airline: "Southwest Airlines",
    fromTime: "05:30 PM",
    toTime: "11:45 PM",
    stops: 1,
    stopLength: "4h 05m in ICN",
    price: 200,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 7,
    from: "BOS",
    to: "DFW",
    departDay: "23-12-2024",
    airline: "JetBlue",
    fromTime: "09:00 AM",
    toTime: "01:30 PM",
    stops: 0,
    stopLength: null,
    price: 275,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 8,
    from: "EWR",
    to: "MCO",
    departDay: "23-12-2024",
    airline: "Frontier Airlines",
    fromTime: "04:15 PM",
    toTime: "07:45 PM",
    stops: 0,
    stopLength: null,
    price: 160,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 9,
    from: "LAS",
    to: "PDX",
    departDay: "23-12-2024",
    airline: "Allegiant Air",
    fromTime: "10:00 AM",
    toTime: "12:30 PM",
    stops: 0,
    stopLength: null,
    price: 140,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 10,
    from: "IAH",
    to: "TPA",
    departDay: "23-12-2024",
    airline: "United Airlines",
    fromTime: "06:45 PM",
    toTime: "09:30 PM",
    stops: 1,
    stopLength: "1.5 hours",
    price: 190,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 11,
    from: "ATL",
    to: "LAX",
    departDay: "23-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 0,
    stopLength: null,
    price: 250,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 12,
    from: "ATL",
    to: "LAX",
    departDay: "23-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 0,
    stopLength: null,
    price: 250,
    airlineLogo: "/airlinelogo3.png",
  },
  {
    id: 13,
    from: "ATL",
    to: "LAX",
    departDay: "23-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 0,
    stopLength: null,
    price: 250,
    airlineLogo: "/airlinelogo3.png",
  },
  {
    id: 14,
    from: "ATL",
    to: "LAX",
    departDay: "23-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 PM",
    stops: 1,
    stopLength: "4h 05m in ICN",
    price: 250,
    airlineLogo: "/airlinelogo1.png",
  },
  {
    id: 15,
    from: "LAX",
    to: "ATL",
    departDay: "27-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 0,
    stopLength: null,
    price: 250,
    airlineLogo: "/airlinelogo3.png",
  },
  {
    id: 16,
     from: "LAX",
    to: "ATL",
    departDay: "27-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 0,
    stopLength: null,
    price: 250,
    airlineLogo: "/airlinelogo3.png",
  },
  {
    id: 17,
     from: "LAX",
    to: "ATL",
    departDay: "27-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 PM",
    stops: 1,
    stopLength: "4h 05m in ICN",
    price: 750,
    airlineLogo: "/airlinelogo1.png",
  }
];
