export const airports = [
  { id: 1, code: "ATL", city: "Atlanta" },
  { id: 2, code: "LAX", city: "Los Angeles" },
  { id: 3, code: "ORD", city: "Chicago" },
  { id: 4, code: "DFW", city: "Dallas" },
  { id: 5, code: "DEN", city: "Denver" },
  { id: 6, code: "JFK", city: "New York" },
  { id: 7, code: "SFO", city: "San Francisco" },
  { id: 8, code: "SEA", city: "Seattle" },
  { id: 9, code: "LAS", city: "Las Vegas" },
  { id: 10, code: "MCO", city: "Orlando" },
  { id: 11, code: "CLT", city: "Charlotte" },
  { id: 12, code: "PHX", city: "Phoenix" },
  { id: 13, code: "IAH", city: "Houston" },
  { id: 14, code: "MIA", city: "Miami" },
  { id: 15, code: "EWR", city: "Newark" },
  { id: 16, code: "BOS", city: "Boston" },
  { id: 17, code: "MSP", city: "Minneapolis" },
  { id: 18, code: "FLL", city: "Fort Lauderdale" },
  { id: 19, code: "DTW", city: "Detroit" },
  { id: 20, code: "PHL", city: "Philadelphia" },
  { id: 21, code: "SAN", city: "San Diego" },
  { id: 22, code: "TPA", city: "Tampa" },
  { id: 23, code: "BWI", city: "Baltimore" },
  { id: 24, code: "SLC", city: "Salt Lake City" },
  { id: 25, code: "HNL", city: "Honolulu" },
  { id: 26, code: "MDW", city: "Chicago" },
  { id: 27, code: "DCA", city: "Washington" },
  { id: 28, code: "STL", city: "St. Louis" },
  { id: 29, code: "PDX", city: "Portland" },
  { id: 30, code: "AUS", city: "Austin" },
];

export const flights = [

  {
    id: 1,
    from: "ATL",
    fromCity: "Atlanta",
    to: "LAX",
    toCity: "Los Angeles",
    departDay: "30-12-2024",
    airline: "Delta Airlines",
    fromTime: "08:00 AM",
    toTime: "11:00 AM",
    stops: 1,
    stopLength: "4h 05m in ICN",
    price: 250,
    airlineLogo: "/airlinelogo1.png",
    bookedSeats: ["1A", "2B", "3C", "4D", "8A", "30A"]
  },
  {
    id: 2,
    from: "ATL",
    fromCity: "Atlanta",
    to: "LAX",
    toCity: "Los Angeles",
    departDay: "30-12-2024",
    airline: "American Airlines",
    fromTime: "09:00 AM",
    toTime: "12:15 PM",
    stops: 0,
    stopLength: "",
    price: 220,
    airlineLogo: "/airlinelogo3.png",
    bookedSeats: ["5A", "10C", "12D", "15B", "20A", "21C"]
  },
  {
    id: 3,
    from: "ATL",
    fromCity: "Atlanta",
    to: "LAX",
    toCity: "Los Angeles",
    departDay: "30-12-2024",
    airline: "United Airlines",
    fromTime: "07:45 AM",
    toTime: "11:10 AM",
    stops: 1,
    stopLength: "2h 30m in DFW",
    price: 240,
    airlineLogo: "/airlinelogo3.png",
    bookedSeats: ["3B", "6A", "9C", "14D", "18B", "28C"]
  },
  {
    id: 4,
    from: "ATL",
    fromCity: "Atlanta",
    to: "LAX",
    toCity: "Los Angeles",
    departDay: "30-12-2024",
    airline: "Spirit Airlines",
    fromTime: "06:30 AM",
    toTime: "10:00 AM",
    stops: 0,
    stopLength: "",
    price: 180,
    airlineLogo: "/airlinelogo4.png",
    bookedSeats: ["2A", "4C", "8D", "11B", "19A", "23C"]
  },
  {
    id: 5,
    from: "ATL",
    fromCity: "Atlanta",
    to: "LAX",
    toCity: "Los Angeles",
    departDay: "30-12-2024",
    airline: "Southwest Airlines",
    fromTime: "10:30 AM",
    toTime: "02:15 PM",
    stops: 1,
    stopLength: "1h 45m in DEN",
    price: 260,
    airlineLogo: "/airlinelogo1.png",
    bookedSeats: ["1C", "5B", "7A", "16D", "25C", "27B"]
  },

  {
    id: 6,
    from: "LAX",
    fromCity: "Los Angeles",
    to: "ATL",
    toCity: "Atlanta",
    departDay: "10-01-2025",
    airline: "Delta Airlines",
    fromTime: "01:00 PM",
    toTime: "06:15 PM",
    stops: 1,
    stopLength: "3h 20m in ORD",
    price: 270,
    airlineLogo: "/airlinelogo1.png",
    bookedSeats: ["2B", "3C", "10A", "14D", "20B", "29A"]
  },
  {
    id: 7,
    from: "LAX",
    fromCity: "Los Angeles",
    to: "ATL",
    toCity: "Atlanta",
    departDay: "10-01-2025",
    airline: "American Airlines",
    fromTime: "02:30 PM",
    toTime: "07:45 PM",
    stops: 0,
    stopLength: "",
    price: 250,
    airlineLogo: "/airlinelogo3.png",
    bookedSeats: ["4A", "6C", "8B", "12D", "18C", "24A"]
  },
  {
    id: 8,
    from: "LAX",
    fromCity: "Los Angeles",
    to: "ATL",
    toCity: "Atlanta",
    departDay: "10-01-2025",
    airline: "United Airlines",
    fromTime: "03:00 PM",
    toTime: "08:15 PM",
    stops: 1,
    stopLength: "1h 50m in PHX",
    price: 260,
    airlineLogo: "/airlinelogo3.png",
    bookedSeats: ["1D", "7B", "9A", "13C", "22B", "28D"]
  },
  {
    id: 9,
    from: "LAX",
    fromCity: "Los Angeles",
    to: "ATL",
    toCity: "Atlanta",
    departDay: "10-01-2025",
    airline: "Spirit Airlines",
    fromTime: "04:45 PM",
    toTime: "10:00 PM",
    stops: 0,
    stopLength: "",
    price: 200,
    airlineLogo: "/airlinelogo4.png",
    bookedSeats: ["3A", "6D", "8B", "15C", "19D", "25B"]
  },
  {
    id: 10,
    from: "LAX",
    fromCity: "Los Angeles",
    to: "ATL",
    toCity: "Atlanta",
    departDay: "10-01-2025",
    airline: "Southwest Airlines",
    fromTime: "05:30 PM",
    toTime: "11:15 PM",
    stops: 1,
    stopLength: "2h 10m in LAS",
    price: 280,
    airlineLogo: "/airlinelogo1.png",
    bookedSeats: ["2C", "5A", "10D", "16B", "21C", "30B"]
  }
];
